version: '3'
services:
  service:
    build: .
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - .env

  elasticsearch:
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'

  redis:
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  load_data_es:
    build:
      context: ./elastic/
      dockerfile: ./elastic.Dockerfile
    env_file:
      - .env
    depends_on:
      - elasticsearch
      
  faker:
    build:
      context: .
      dockerfile: ./faker/faker.Dockerfile
    env_file:
      - ./.env
    depends_on:
      - elasticsearch

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/configs:/etc/nginx/conf.d:z
    depends_on:
      - service
    ports:
      - "80:80"
