version: '3'
services:
  service:
    ports:
      - "8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - "9200:9200"

  redis:
    image: redis:7.0.10-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.23.3