version: '3'
services:
  service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - .env
    command: ["gunicorn", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "src.main:app", "--bind", "$APP_HOST:$APP_PORT"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0  
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'

  redis:
    image: redis:7.0.10-alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  load_data_es:
    build:
      context: ./elastic/
      dockerfile: ./elastic.Dockerfile
    env_file:
      - .env
    depends_on:
      - elasticsearch
      
  faker:
    build:
      context: .
      dockerfile: ./faker/faker.Dockerfile
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
