# название
name: Project test & build

on:
  push:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Create Issues From Files
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: ./tasks/*
          labels:
            report
            automated issue